services:
  redis:
    image: 'redislabs/redismod'
    networks:
    - app_net
  web1:
    restart: on-failure
    build: ./web
    image: ${SERVER_IMAGE}
    hostname: web1
    networks:
    - app_net
  web2:
    restart: on-failure
    image: ${SERVER_IMAGE}
    build: ./web
    hostname: web2
    networks:
    - app_net
  nginx:
    image: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/conf.d/default.conf
    networks:
    - app_net
    depends_on:
    - web1
    - web2

networks:
  app_net:


